### ISSUE TITLE
Allow all 3 components and mysql to be on separate instances/docker containers

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#100]
Please tell if it is possible to have all that processes run on separate machines? Or it is designed only to be run on a single instance? I've built all 3 docker containers for them, but have no idea how to connect them to each other and to mysql

**Comment by NashMiao** [comment]
I think more information is needed. For example, you can run `OntSynHandler` in one machine, and run multi `Explorer` in other machines.

**Comment by ksemaev** [comment]
Done, dockerfiles are pushed to repo
