### ISSUE TITLE
Update readme for version2.0

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#101]
The settings are now located in several springboot profile files. The default is set as `spring.profiles.active=dev`.  

Also, as in all profiles masternode is specified as local `masternode.restful.url = http://127.0.0.1:20334` we need to mention that either local installation needed, or uncomment the public masternode address

When trying to build with `application-dev` profile - you need to define `spring.datasource.password=${MYSQL_TEST_PASSWORD}`, where as in other profiles the password is hardcoded.

**Comment by ksemaev** [comment]
Readme says to 

> Firstly, cd the OntSynHandler project lib directory

But there's no such directory 

https://github.com/ontio/ontology-explorer/issues/104

**Comment by NashMiao** [comment]
@ksemaev Hi, you can replace `${MYSQL_TEST_PASSWORD}` with your own MySQL password. Besides, I think hard coded password in profiles should be forbidden.

**Comment by ksemaev** [comment]
@NashMiao TY, already did, now it builds fine, I can share docker files later if needed

**Comment by NashMiao** [comment]
> @NashMiao TY, already did, now it builds fine, I can share docker files later if needed

wonderful! we need this, thank your.
