### ISSUE TITLE
Test for mysql fails, but summary says all's good

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#103]
Fetched repo, created mysql with empty db, trying `mvn clean package` and receive multiple:
```
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table 'explorer.tbl_oep4' doesn't exist
```

But still as the result I see **[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0**

Shouldn't test fail when there's no tables created it mysql yet?

**Comment by ksemaev** [comment]
BTW should I run all scripts in `sql` directory myself? I couldn't find anything calling them

**Comment by NashMiao** [comment]
> BTW should I run all scripts in `sql` directory myself? I couldn't find anything calling them

Right, you need to run them to create table in your database.

**Comment by ksemaev** [comment]
@NashMiao I use only `version2.0 ` and create all issues only for it, TY!

**Comment by NashMiao** [comment]
> Shouldn't test fail when there's no tables created it mysql yet?

In fact, The UT needed to be added  into this project . Currently, the tests folder is meaningless.
