### ISSUE TITLE
Build of OntSysHandler looking for ontology-sdk-java.jar

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#104]
The `ontology-sdk-java.jar` is located in `ontology-explorer/back-end-projects/Explorer/lib` (BTW git repo is not supposed to keep .jar files inside, please move them to dependencies. or maybe be build during build).

So in order OntSysHandler could be built successfully I need to copy that jar to my `OntSysHandler` directory from `Explorer`:
```
cp -R back-end-projects/Explorer/lib back-end-projects/OntSynHandler/
```

Is that even fine way to go?

**Comment by NashMiao** [comment]
@ksemaev Hi, you can publish `ontology-sdk-java.jar` to your own maven repository.

```
git clone https://github.com/ontio/ontology-java-sdk.git
```

I will publish the newest release sdk to the public maven repository in this week.

**Comment by NashMiao** [comment]
@ksemaev Hi, I had deployed ontology-java-sdk v1.0.13 to [Maven Central Repository](https://mvnrepository.com/artifact/com.github.ontio/ontology-sdk-java/1.0.13). You can try to use it. If you have any issue about ontology-java-sdk, you can open new issue in [here](https://github.com/ontio/ontology-java-sdk/issues). I will close this issue as the end of this dependency problem.

**Comment by ksemaev** [comment]
@NashMiao any change of the instructions than? How will I need to build it from now on? Like this:
```
maven package
mvn install:install-file -DgroupId=com.github.ontio -DartifactId=javasdk -Dversion=v1.0 -Dpackaging=jar -Dfile=ontology-sdk-java.jar
maven clean package
```

Something like this ^^ ? Or how cah I get this dependency for build?
