### ISSUE TITLE
Different settings for OntSysHandler and Explorer backend projects

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#105]
First of all they point to different mysql DB in their application-dev spring profiles, is that fine?:
-  `spring.datasource.url=jdbc:mysql://127.0.0.1:3306/explorer_v2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC` or **explorer_v2** for explorer;
-  `spring.datasource.url = jdbc:mysql://127.0.0.1:3306/explorer?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&serverTimezone=UTC` or **explorer** for OntSysHandler;

Also if we use env var as mysql password for OntSysHandler, maybe let's do the same for Exporer, where it is hardcoded? (https://github.com/ontio/ontology-explorer/blob/version2.0/back-end-projects/OntSynHandler/config/application-dev.properties#L21 vs https://github.com/ontio/ontology-explorer/blob/version2.0/back-end-projects/Explorer/config/application-dev.properties#L13) ?

**Comment by NashMiao** [comment]
They should be point to same database. I think this is error commit.

**Comment by ksemaev** [comment]
@NashMiao if you don't mind - please do not close issue, until it is fixed. And please specify the issue in fixing commit, so we can be sure it is fixed.
TY!

**Comment by NashMiao** [comment]
@ksemaev sorry, I will reopen it.
