### ISSUE TITLE
SQL scripts confusion

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#107]
Which directory should I take sql scripts from? `ontology-explorer/back-end-projects/Explorer/sql` or `ontology-explorer/back-end-projects/OntSynHandler/sql` ? They vary in number and content.

Should I apply all of them? In which order?

**Comment by NashMiao** [comment]
I think you need to run the SQL scripts in `Explorer/sql`, it contain the SQL scripts in [this](https://github.com/NashMiao/ontology-explorer-summary) repository.

**Comment by ksemaev** [comment]
@NashMiao surely, TY! All of them? In which order?

**Comment by NashMiao** [comment]
All the scripts in `ontology-explorer/back-end-projects/Explorer/sql`. If you need some summary information, you also need to run [this](https://github.com/NashMiao/ontology-explorer-summary) project.
