### ISSUE TITLE
Feature request: add vars for other changing settings

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#108]
Can we please consider using same vars as here https://github.com/ontio/ontology-explorer/blob/version2.0/back-end-projects/OntSynHandler/config/application-dev.properties#L21 for:
- spring.datasource.username;
- DB address;
- DB port;
- DB name;
- masternode.restful.url;
- goserver.domain.

**Comment by NashMiao** [comment]
okay, I will try to handle this.
