### ISSUE TITLE
Urge request for creating tags/releases

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#117]
Guys you did few comments to the same `version2.0` branch, and it broke the builds, as from now on the explorer build results `explorer-1.1.0.RELEASE.jar` instead of `explorer-1.0.0-SNAPSHOT.jar`

Let's try to keep such huge changes to the next release, with mentioning what really changed in that release, so people would be aware. And maybe work out some naming convention for build artifacts.

TY!

**Comment by NashMiao** [comment]
sorry, I will try to create tags, but it needs some time, this project need to be clean up.
