### ISSUE TITLE
version

### ISSUE THREAD

**Issue by 740459382** [ontio/ontology-explorer#12]
com.github.ontio.javasdk dependency 1.0 ?

**Comment by zzsZhou** [comment]
mvn install:install-file -DgroupId=com.github.ontio -DartifactId=javasdk -Dversion=vXXX -Dpackaging=jar -Dfile=ontology-sdk-java.jar
上面的maven打包命令里的-Dversion参数可以随便指定，只要在pom.xml里引用sdk版本号一样就行
		<dependency>
			<groupId>com.github.ontio</groupId>
			<artifactId>javasdk</artifactId>
			<version>vXXX</version>
		</dependency>
