### ISSUE TITLE
empty responses from explorer

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#124]
When I try to get transactions for any address, for example `v2/addresses/APKUmRKRdqunZHLuHyLu2h3zU8jMKFQtR9/transactions` I get null response:
> {"code":null,"msg":null,"result":null}

 In the logs of explorer I see that: 
> [ INFO ] [2019-07-03 12:30:21] com.github.ontio.controller.AddressController [62] - ####AddressController.queryAddressTransferTxsByPage begin...address:APKUmRKRdqunZHLuHyLu2h3zU8jMKFQtR9

In the logs of ontsynhandler I see that:

> [ INFO ] [2019-07-03 11:47:32] com.github.ontio.thread.TxHandlerThread [126] - eventLog:{"GasConsumed":10000000,"Notify":[{"States":["transfer","APKUmRKRdqunZHLuHyLu2h3zU8jMKFQtR9","ANEA4afVH5ZEoNDeSkErUnzr7RMY8bHTaK",1],"ContractAddress":"0100000000000000000000000000000000000000"},{"States":["transfer","APKUmRKRdqunZHLuHyLu2h3zU8jMKFQtR9","AFmseVrdL9f9oyCzZefL9tG6UbviEH9ugK",10000000],"ContractAddress":"0200000000000000000000000000000000000000"}],"TxHash":"d0e8023a272c1bb37ce2cd7206b02cf08fde0ef4bea68b4422a248d7df8fae4e","State":1}

**Comment by NashMiao** [comment]
@ksemaev Hi, I think this is a bug. In fact, you need to specify the `pageNumber`, `pageSize` or `beginTime`, `endTime`.

The code you can read in [here](https://github.com/ontio/ontology-explorer/blob/3295fce6882e88d9d43a7af095683c1098604117/back-end-projects/Explorer/src/main/java/com/github/ontio/controller/AddressController.java#L91).

**Comment by NashMiao** [comment]
![image](https://user-images.githubusercontent.com/18191964/60636099-b353f000-9e47-11e9-968a-bf4a20e2351a.png)

Hi, this is an example from [Explorer](https://explorer.ont.io/address/APKUmRKRdqunZHLuHyLu2h3zU8jMKFQtR9/ALL/20/2).

**Comment by ksemaev** [comment]
@NashMiao TY for explaining, it does work that way!
