### ISSUE TITLE
ontology-explorer backend restart error

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#125]
If I try to restart container with ontology-explorer I get the same error I had before:

> [ ERROR] [2019-07-05 07:37:20] org.springframework.boot.SpringApplication [842] - Application run failed
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'BlockService' defined in URL [jar:file:/home/ontology/app.jar!/BOOT-INF/classes!/com/github/ontio/service/impl/BlockServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'blockMapper' defined in URL [jar:file:/home/ontology/app.jar!/BOOT-INF/classes!/com/github/ontio/mapper/BlockMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'class path resource [mapper/Oep4TxDetailMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. The XML location is 'class path resource [mapper/Oep4TxDetailMapper.xml]'. Cause: org.apache.ibatis.cache.CacheException: Could not instantiate cache implementation (class com.github.ontio.config.RedisCache). Cause: java.lang.reflect.InvocationTargetException

Only full restart/recreate of redis cluster fixes the issue. This has to be resolved somehow on code level, @NashMiao please advice.

To test - just restart ontology-explorer without restarting redis.

**Comment by NashMiao** [comment]
I need to take some time to reproduce this issue in my computer. Could you please provide me the steps to reproduce the behavior?

**Comment by ksemaev** [comment]
Sure. let me create some playground for it

**Comment by aweigold** [comment]
I actually have the root cause identified to this with a solution.  I'll submit a PR tomorrow.  Issue is a race condition between the spring context initializing and MyBatis instantiating the RedisCache.

**Comment by NashMiao** [comment]
@aweigold Thanks for your help.
