### ISSUE TITLE
Latest build of ontexplorer fails to pass tests

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#132]
@NashMiao please advice, I receive this when trying to build from `6e529790016891c28200ff8b7840522a00696cba` (supposed fix for https://github.com/ontio/ontology-explorer/issues/125#event-2488566025):

> [INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.185 s - in com.github.ontio.BasicTest
> [INFO] 
> [INFO] Results:
> [INFO] 
> [ERROR] Errors: 
> [ERROR]   DemoApplicationTests.contextLoads » IllegalState Failed to load ApplicationCon...
> [ERROR]   updateContractInfoTest.updateContract » IllegalState Failed to load Applicatio...
> [INFO] 
> [ERROR] Tests run: 5, Failures: 0, Errors: 2, Skipped: 

Should I disable tests , or you can fix it?

**Comment by ksemaev** [comment]
Tried to run the version with skipped tests and got this:

> [ ERROR] [2019-07-17 09:13:02] org.springframework.boot.SpringApplication [842] - Application run failed
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'OntIdService' defined in URL [jar:file:/home/ontology/app.jar!/BOOT-INF/classes!/com/github/ontio/service/impl/OntIdServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ParamsConfig': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'dapp.reward.percentage' in value "${dapp.reward.percentage}"

**Comment by aweigold** [comment]
The tests are working here for myself from a clean checkout of the version2.0 branch.  Could you post the surefire-reports from the target folder showing the test failure?

**Comment by ksemaev** [comment]
@aweigold  You can reproduce it with dockerfile:
```
################################
### Builder image
################################
FROM maven:3.6.1-slim

ENV VERSION=6e529790016891c28200ff8b7840522a00696cba \
    ONTOLOGY_MYSQL_ADDRESS=localhost \
    ONTOLOGY_MYSQL_DBNAME=explorer \
    ONTOLOGY_MYSQL_USER=ontology \
    ONTOLOGY_MYSQL_PASSWORD=qwerty \
    ONTOLOGY_REDIS_ADDRESS=localhost \
    ONTOLOGY_REDIS_PASSWORD=qwerty \
    ONTOLOGY_NODE_ADDRESS=dappnode1.ont.io \
    ONTOLOGY_NODE_PORT=20334

RUN apt update && \
    apt install -y \
    git

RUN git clone https://github.com/ontio/ontology-explorer.git && \
    cd ontology-explorer && \
    git checkout $VERSION

COPY application-dev.properties /ontology-explorer/back-end-projects/Explorer/config/

WORKDIR /ontology-explorer

RUN cd back-end-projects/Explorer && \
    mvn clean package
```

**Comment by ksemaev** [comment]
Just ran it on my mac^^ And received the same error

**Comment by aweigold** [comment]
I just ran the build from your commit id with your env vars from `maven:3.6.1-slim` here, and the build succeeded.  Likely what is happening is that there are properties you are changing in the dev profile which are failing the Spring test app context.

You could resolve this by moving the `COPY` command after the build.  That said however, it wouldn't change your runtime error you also mentioned.

Looking at the base `application-dev.properties` file, the missing property you have in your error exists (with a recent commit on 2019-07-05).  You could rebase from it.  A better way however to manage this for yourself however would be to take the following steps (these are undocumented by ontio, but this is supported by Spring):
- Make a new property file with just your overrides, call it `application-<my-org>.properties`
- Copy that property file to the config location.
- Set the env variable `SPRING_ACTIVE_PROFILES=<my-org>`.

Let me know if that works for you.

**Comment by ksemaev** [comment]
@aweigold TY! I indeed had my custom properties file, which I created just for replacing connection settings with vars (to have different var values in different envs), like this:

> spring.datasource.url=jdbc:mysql://ONTOLOGY_MYSQL_ADDRESS:3306/ONTOLOGY_MYSQL_DBNAME?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
hence: https://github.com/ontio/ontology-explorer/issues/108

And seems like my current config is missing those values:
```
reqlimit.expire.millisecond=1000
dapp.reward.percentage=60
node.reward.percentage=30
balanceservice.host=http://192.168.3.88:20334
querybalance.mode=0
```

**Comment by ksemaev** [comment]
Yep, my custom config was the reason for tests to fail, closing this one up
