### ISSUE TITLE
balanceservice.host option

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#139]
When I comment out `balanceservice.host` in application-dev.properties I get this error:

> [ ERROR] [2019-07-19 14:22:32] org.springframework.boot.SpringApplication [842] - Application run failed
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ContractService' defined in URL [jar:file:/home/ontology/app.jar!/BOOT-INF/classes!/com/github/ontio/service/impl/ContractServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 6; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ParamsConfig': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'balanceservice.host' in value "${balanceservice.host}

By default it's value is `http://192.168.3.88:20334` - https://github.com/ontio/ontology-explorer/blob/version2.0/back-end-projects/Explorer/config/application-dev.properties#L82

What is that? should I have some balancers? What value should be placed there if I have none?
@NashMiao please advice

**Comment by NashMiao** [comment]
sorry, please change this value to `dappnode01.ont.io:20334`, the default value only support internal access.
