### ISSUE TITLE
Numerous ontsynhandler issues

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#140]
I get such logs from time to time (it has a lot of `?` signe in it):

> ### Cause: com.mysql.cj.jdbc.exceptions.PacketTooBigException: Packet for query is too large (22,068,986 > 4,194,304). You can change this value on the server by setting the 'max_allowed_packet' variable.
> ; Packet for query is too large (22,068,986 > 4,194,304). You can change this value on the server by setting the 'max_allowed_packet' variable.; nested exception is com.mysql.cj.jdbc.exceptions.PacketTooBigException: Packet for query is too large (22,068,986 > 4,194,304). You can change this value on the server by setting the 'max_allowed_packet' variable.

**Comment by NashMiao** [comment]
Try to find out the `max_allowed_packet` in your MySQL Server like this:

![image](https://user-images.githubusercontent.com/18191964/61572942-6c692a00-aad8-11e9-9115-bcfc93927ba7.png)

Then, change this value to a greater number:

```SQL
SET GLOBAL max_allowed_packet=23000000;
```

**Comment by ksemaev** [comment]
OK, I'm using AWS RDS and it seems like I can't do it from mysql cli 
@Merlz can you please look at it, and mention in TF code?
