### ISSUE TITLE
Unbound ONG not updated on receive

### ISSUE THREAD

**Issue by nickfujita** [ontio/ontology-explorer#16]
ONG is granted to an account upon send and receipt of ONT. The `Claimable ONG` amount is updated when an address receives ONT, but the `Unbound ONG` amount is still calculated from the last address send event (or genesis block if no send transactions). Both `Claimable ONG` and `Unbound ONG` are updated properly when ONT is sent from address.

Steps to reproduce:
- Open address A in explorer
- Send ONT from address B to address A

Expected result:
- address A `Unbound ONG` calculation should be updated since last transaction. In this case the recent receive of ONT

Actual result:
- address A `Unbound ONG` calculation remains unchanged, and is since last send or genesis block

**Comment by sulingxiao** [comment]
We did not maintain a real-time update of the balance.
Just refresh the page to see the results.
