### ISSUE TITLE
Failed tx and confirm_flag

### ISSUE THREAD

**Issue by roccomuso** [ontio/ontology-explorer#167]
I noticed a `failed` tx has `confirm_flag` property to `0`. 
But how do you differentiate between unconfirmed txs and failed txs?

**Comment by NashMiao** [comment]
@roccomuso sorry, could you provide more details about this issue?

**Comment by roccomuso** [comment]
listed transactions have a `confirm_flag` that can be 0 or 1.
Anyway looks like that `confirm_flag` relates only to good or bad transaction. Is not related to a tx being confirmed (put in a block) or not.

**Comment by NashMiao** [comment]
The value of `confirm_flag` come from contract event‘s state. You can find the code in [here](https://github.com/ontio/ontology-explorer/blob/f270983ad110fca32d384c880e58e7ed4b203b3b/back-end-projects/OntSynHandler/src/main/java/com/github/ontio/thread/TxHandlerThread.java#L130).

Therefore, this flag indicated wether the execution of smart contract in this transaction has been execute successfully.

For example, [this transaction](https://explorer.ont.io/transaction/0025933f5f536a2ebbd0049ef14ce45b75cd4b99ed4d2c544a40156a7372e54d) has been confirmed by consensus nodes and be written into block. However, the execution of smart contract in this transaction failed with the `states` flag setted to `0`.

![image](https://user-images.githubusercontent.com/18191964/63321395-2a3f3c80-c353-11e9-8616-cfb2b6c1895c.png)
