### ISSUE TITLE
Sync is  stoping on 1086411.

### ISSUE THREAD

**Issue by matyushkins** [ontio/ontology-explorer#211]
Hi sync is stoping on 1086411.

> ont-sync             | [ INFO ] [2020-02-25 08:41:02] com.github.ontio.thread.TxnHandlerThread [69] - TxnHandlerThread--1 run--------blockHeight:1086412
ont-sync             | [ INFO ] [2020-02-25 08:41:02] com.github.ontio.thread.TxnHandlerThread [82] - ####txnType:208, txnHash:e0e62717c5a52dc95c229c5262015dd5610eb882fdf3abdf6f74718d8ace0818####
ont-sync             | [ INFO ] [2020-02-25 08:41:02] com.github.ontio.thread.TxnHandlerThread [88] - eventObj:{"GasConsumed":11500000000,"Notify":[{"States":["transfer","AdM8XvgyU9cnTFJedsssk597U2xGG8vZUb","AFmseVrdL9f9oyCzZefL9tG6UbviEH9ugK",11500000000],"ContractAddress":"0200000000000000000000000000000000000000"}],"TxHash":"e0e62717c5a52dc95c229c5262015dd5610eb882fdf3abdf6f74718d8ace0818","State":1}
ont-sync             | [ INFO ] [2020-02-25 08:41:02] org.springframework.jmx.export.annotation.AnnotationMBeanExporter [433] - Registering beans for JMX exposure on startup
ont-sync             | [ INFO ] [2020-02-25 08:41:02] org.springframework.jmx.export.annotation.AnnotationMBeanExporter [895] - Bean with name 'dataSource' has been autodetected for JMX exposure
ont-sync             | [ INFO ] [2020-02-25 08:41:02] org.springframework.jmx.export.annotation.AnnotationMBeanExporter [668] - Located MBean 'dataSource': registering with JMX server as MBean [com.zaxxer.hikari:name=dataSource,type=HikariDataSource]
ont-sync             | [ INFO ] [2020-02-25 08:41:02] org.apache.coyote.http11.Http11NioProtocol [180] - Starting ProtocolHandler ["http-nio-8090"]
ont-sync             | [ INFO ] [2020-02-25 08:41:02] org.apache.tomcat.util.net.NioSelectorPool [180] - Using a shared selector for servlet write/read
ont-sync             | [ INFO ] [2020-02-25 08:41:02] org.springframework.boot.web.embedded.tomcat.TomcatWebServer [206] - Tomcat started on port(s): 8090 (http) with context path ''
ont-sync             | [ INFO ] [2020-02-25 08:41:02] com.github.ontio.OntsynhandlerApplication [59] - Started OntsynhandlerApplication in 3.94 seconds (JVM running for 4.342)
ont-sync             | [ ERROR] [2020-02-25 08:41:02] com.github.ontio.thread.TxnHandlerThread [172] - handleOneTxn RestfulException...{}
ont-sync             | com.github.ontio.network.exception.RestfulException: {"Action":"getcontract","Desc":"INTERNAL ERROR","Error":45001,"Result":"","Version":"1.0.0"}
ont-sync             | 	at com.github.ontio.network.rest.RestClient.getContractJson(RestClient.java:191)
ont-sync             | 	at com.github.ontio.sdk.manager.ConnectMgr.getContractJson(ConnectMgr.java:220)

**Comment by zzsZhou** [comment]
Which branch do you use?may you can use the latest branch version2.1.0.

**Comment by xizho10** [comment]
Please use branch version2.1.0. This is our latest version.
