### ISSUE TITLE
Some new sql tables appeared

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#215]
I'm building from `version2.1.0-release` and facing the problem with ```Table 'ontdb.tbl_tx_detail_index' doesn't exist```

Guys you keep silently changing mysql layout, can you please post all the changes that needed to be done manually? Where can I see what are the current tables? Should I resync from 0?

**Comment by ksemaev** [comment]
Tried searching in all that we have here: https://github.com/ontio/ontology-explorer/tree/version2.1.0-release/back-end-projects/Explorer/sql  but no script with such name exists.

**Comment by ksemaev** [comment]
@zzsZhou can I have your attention here? This issue is preventing me from upgrade to the first and only release we're having here

**Comment by zzsZhou** [comment]
Sorry for the late reply,we release version2.1.1 to add the missing configuration parameters and SQL.And the all sql scripts in the Explorer path:\src\main\resources\db\migration.
You can use flyway(https://flywaydb.org/) to manage the sql scripts.

**Comment by ksemaev** [comment]
@zzsZhou  ty for responding! New error is 
`### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Table 'ontdb.tbl_user' doesn't exist`

**Comment by ksemaev** [comment]
@zzsZhou is ontsynhandler doing something huge at startup now? After I run all migrations - it started with 

> [ WARN ] [2020-05-08 12:19:22] org.mybatis.spring.mapper.ClassPathMapperScanner [44] - No MyBatis mapper was found in '[com.github.ontio]' package. Please check your configuration.
> Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

And logging nothing for 30 min already. Metrics show that it consumes 0,2 cores and 500Mb RAM all this time.

**Comment by ksemaev** [comment]
first log came after 2 hours of waiting: 

> [ ERROR] [2020-05-08 14:02:07] com.github.ontio.service.CommonService [455] - getContractJson error...
com.github.ontio.network.exception.RestfulException: {"Action":"getcontract","Desc":"INTERNAL ERROR","Error":45001,"Result":"","Version":"1.0.0"}

Please advice

**Comment by zzsZhou** [comment]
[ ERROR] [2020-05-08 14:02:07] com.github.ontio.service.CommonService [455] - getContractJson error...
com.github.ontio.network.exception.RestfulException: {"Action":"getcontract","Desc":"INTERNAL ERROR","Error":45001,"Result":"","Version":"1.0.0"}

This error occurred when cannot find the contract on the blockchain,maybe the contract has been removed from blockchain or you are connected to the wrong network.You can try the right network or ignore this error,this error does not break the program.

**Comment by ksemaev** [comment]
Indeed, it's syncing up, TY!
