### ISSUE TITLE
About the 'getAssetHolderCount' API problem

### ISSUE THREAD

**Issue by Phoenix117** [ontio/ontology-explorer#29]
Does anyone know that if the 'getAssetHolderCount' api is in the ontology-explorer project?
I can't change the 'EXPLORE_URL' in the prod.env.js, or the result of 'getAssetHolderCount' api will be 404.
And I can't find the 'getAssetHolderCount' api in the code of ontology-explorer project.

**Comment by Jaraxuss** [comment]
同问。

**Comment by NashMiao** [comment]
@Phoenix117 @Jaraxuss No, it's another service written in Go.

You can use it in following URL:

https://explorer.ont.io/getAssetHolder?qid=1&contract=0100000000000000000000000000000000000000&from=0&count=20
