### ISSUE TITLE
Endpoint /v2/nodes/current-stakes not working

### ISSUE THREAD

**Issue by muratso** [ontio/ontology-explorer#315]
Hey guys, we're currently trying to use the latest commit and we can't get this endpoint working properly. 
We get the error
```
{
  "code": 61003,
  "msg": "FAIL, not found.",
  "result": []
}
```
and there's nothing in the logs that help to troubleshoot this. Any thoughts here?

**Comment by muratso** [comment]
cc: @leej1012

**Comment by leej1012** [comment]
The data of "Endpoint /v2/nodes" is synchronized by another statistics server:https://github.com/ontio-community/explorer-statistics.git

If you need use Endpoint /v2/nodes, please start the statistics server as well.

**Comment by muratso** [comment]
@leej1012 thank you so much. It's working now. However, the endpoint `/v2/nodes/block-count-to-next-round` is still not not working. It's failing with the error
```
{
"code": 63001,
"msg": "FAIL, inner error.",
"result": ""
}```
But again the logs are not being very helpful as they don't throw any error. Any thoughts here?

**Comment by leej1012** [comment]
@muratso Please check whether there is data in the table :`tbl_node_overview`,`tbl_config`.

If `tbl_config` is empty, try to execute SQL:
INSERT INTO `tbl_config`(`field`, `value`) VALUES ('maxStakingChangeCount', '60000');

By the way, the statistics server branch is also version2.1.0

**Comment by muratso** [comment]
Thank you so much! Everything working on our side now! Closing this issue. I have another question but I'm gonna open a new issue since it's a different problem. Thank you so much!
