### ISSUE TITLE
Mismatched transactions

### ISSUE THREAD

**Issue by WyattMufson** [ontio/ontology-explorer#95]
The explorer is not showing the correct tx count. For example: https://explorer.ont.io/contract/all/0f3384d015e7d569283dc4e1a8be64b101c90299/10/3

It says 256 but has 482 rows. Under addresses it says 2, but that is the amount of invokers on the contract, not the amount of wallets that have signed txs.

**Comment by NashMiao** [comment]
V2 is the current version of the explorer api, still in the process of perfection, etc. We will announce it when the degree of completion is higher.

We will update the v1 version and keep it consistent with v2.
