### ISSUE TITLE
Using tags/releases for fixed code versions

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#96]
Guys, I know that I can use git tools for pointing to exact commit hash, but for CI/CD simplicity and transparency can you consider using tags and/or create github releases?

**Comment by sulingxiao** [comment]
> Guys, I know that I can use git tools for pointing to exact commit hash, but for CI/CD simplicity and transparency can you consider using tags and/or create github releases?

Of course, thank you very much for your advice!

**Comment by ksemaev** [comment]
Please tag current version than, if it's possible
