### ISSUE TITLE
Build of the OntSynHandler is failing 

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#98]
When following the instruction in Readme, trying to build the code with maven, I hit an error on step `mvn install:install-file -DgroupId=com.github.ontio -DartifactId=javasdk -Dversion=v1.0 -Dpackaging=jar -Dfile=ontology-sdk-java.jar`:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file (default-cli) on project ontsynhandler: The specified file '/ontology-explorer/back-end-projects/OntSynHandler/ontology-sdk-java.jar' not exists -> [Help 1]
```

As there's no such file. Maybe some readme updates needed, or I should look for instructions anywhere else?

**Comment by darkverbito** [comment]
First you need to build the Explorer like this:

**Comment by ksemaev** [comment]
@darkverbito TY, could you please update readme if possible

**Comment by ksemaev** [comment]
I will continue trying to build the code, while posting the problems I'm facing with here. So explorer builds fine, but steps for ontsyshandler 
`cd back-end-projects/OntSynHandler && \
    mvn package && \
    cd lib && \
    mvn install:install-file -DgroupId=com.github.ontio -DartifactId=javasdk -Dversion=v1.0 -Dpackaging=jar -Dfile=ontology-sdk-java.jar && \
    cd .. && \
    mvn clean package`

results:
```
[ ERROR] [2019-06-21 07:55:40] org.springframework.boot.SpringApplication [858] - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'baseDruidConfig': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'MYSQL_TEST_PASSWORD' in value "${MYSQL_TEST_PASSWORD}"
```

So what is doing with mysql? I will add it to container now, but just curious

**Comment by darkverbito** [comment]
It's getting hung up on an unset variable in a test. The variable is located in `back-end-projects/OntSynHandler/config/application-dev.properties` here `spring.datasource.password=${MYSQL_TEST_PASSWORD}`. Since you don't care about the tests for building purposes you can set that variable like this: ```export MYSQL_TEST_PASSWORD="" && mvn package``` which will allow the build to complete.
```
```

**Comment by ksemaev** [comment]
As springboot's default profile is set to be dev, and in dev the mysql password is passed as variable (opposed to other profiles, where it is hardcoded) - you really need to pass actual mysql password here. Created a separate issue with multiple readme updates request
