### ISSUE TITLE
Allow front-end to accept calls for any URL

### ISSUE THREAD

**Issue by ksemaev** [ontio/ontology-explorer#99]
Right now I'm trying to build a separate frontend instance/docker image.

I tried to use that `prod.env.js` file (removed ssl and renamed URI to localhost):

```
'use strict';

module.exports = {
  NODE_ENV: '"production"',

  // 单独提供给addresses页面的接口，golang实现的
  EXPLORE_URL: '"http://localhost/"',
  TEST_EXPLORE_URL: '"https://polarisexplorer.ont.io/"',

  // 基础API接口
  API_URL: '"http://localhost/api/v1/explorer"',
  TEST_API_URL: '"https://polarisexplorer.ont.io/api/v1/explorer"',

  // 提供节点统计信息计算查询的接口：
  DAPP_NODE_URL: '"https://dappnode1.ont.io:10334"',
  TEST_DAPP_NODE_URL: '"http://139.219.128.220:20334"',

  NET:true
};
```

So now I can see main page on http://localhost, but http://localhost/api/v1/explorer gives me 404, and nginx is reasonably saying that `[error] 6#6: *7 open() "/usr/share/nginx/html/api/v1/explorer" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /api/v1/explorer HTTP/1.1", host: "localhost"
172.17.0.1 - - [21/Jun/2019:13:01:28 +0000] "GET /api/v1/explorer HTTP/1.1" 404 153 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0" "-"`

So where exactly is that `api/v1/explorer` should point to? What is missing?

**Comment by sulingxiao** [comment]
Hi, dear friend, you should point it to a server that launches the explorer background service.
https://github.com/ontio/ontology-explorer/tree/master/back-end-projects

Like our explorer is pointing to https://explorer.ont.io/

**Comment by ksemaev** [comment]
@sulingxiao TY very much for explaining! Will try it and report the results here

**Comment by ksemaev** [comment]
@sulingxiao please advice on general scheme than: 
1) OntSysHandler is connecting to ONT node and fills mysql;
2) Backend-explorer is connecting to mysql and exposes api to access it;
3) Frontend-explorer is just nginx proxying calls to backend-explorer;
Am I right, or I miss some connections between components here?

**Comment by ksemaev** [comment]
@NashMiao maybe you can explain this arcitecture question here as well please?

**Comment by NashMiao** [comment]
> @sulingxiao please advice on general scheme than:
> 
> 1. OntSysHandler is connecting to ONT node and fills mysql;
> 2. Backend-explorer is connecting to mysql and exposes api to access it;
> 3. Frontend-explorer is just nginx proxying calls to backend-explorer;
>    Am I right, or I miss some connections between components here?

@ksemaev Sorry for late. Absolutely, you are right. This is all the architecture of ontology-explorer. Currently, statistical services split from ontology-explorer and become a new project in [here](https://github.com/NashMiao/ontology-explorer-summary).

**Comment by ksemaev** [comment]
@NashMiao TY for explainig! But why then `ontsyshandler` starts a tomcat on specified port? Do we access it from anywhere?

**Comment by ksemaev** [comment]
And also I'm confused: which part of `ontology-explorer` went to `ontology-explorer-summary`? Is it frontend? Will you provide a short instruction on it's build?
